version: "2"
services:
  front-end:
    container_name: awesome_react
    build: front-end
    volumes:
      - ./front-end:/var/html/app
      - /var/html/app/node_modules
    ports:
      - "3000:3000"
  mongo:
    container_name: fantastic_mongo
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodata:
